



use interface

db.soap_request_mapping.insert({     "_id" : NumberLong(1023),"end_point_url" : "","url_type" : "POST","interface_code" : "SNOC1004","interface_id" : NumberLong(1023),"interface_name" : "XML_REQUEST_CONVERTER","interface_description" : "XML_REQUEST_CONVERTER","interface_type" : "","operation" : "publish","auth_uname" : "","auth_pwd" : "",     "request" : "<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:typ=\"http://ws/its/tabs/webservices/ordermangement/OrderManagement.wsdl/types/\">  <soapenv:Header/>  <soapenv:Body>  <typ:retailerDetailsElement>  <typ:RetailerName>${retailerDetails/RetailerName}</typ:RetailerName>  <typ:RetailerId>${retailerDetails/RetailerId}</typ:RetailerId>  <typ:RetailerAmount>${retailerDetails/RetailerAmount}</typ:RetailerAmount>  </typ:retailerDetailsElement> </soapenv:Body> </soapenv:Envelope>",     "res_attributes" : {         "response_code" : ""     },     "status_config" : {         "failed_status" : NumberLong(115)     },     "system_name" : "SNOC",     "tracking_required" : false })
db.soap_request_mapping.insert({     "_id" : NumberLong(1040),"end_point_url" : "https://api.razorpay.com/v1/payments/${payment_gateway_ref_id}","url_type" : "GET","interface_code" : "SNOC1004","interface_id" : NumberLong(1040),"interface_name" : "GET_PAYMENT_DETAILS_BY_ID","interface_description" : "GET_PAYMENT_DETAILS_BY_ID","interface_type" : "",     "operation" : "publish",     "auth_uname" : "rzp_test_Fk3ZT6fd3w62HC",     "auth_pwd" : "wgbQXRZtyQAUhDtx59acUeij",     "url_attributes" : [         "payment_gateway_ref_id"     ],     "res_attributes" : {         "response_code" : ""     },     "status_config" : {         "failed_status" : NumberLong(400)     },     "system_name" : "SNOC",     "tracking_required" : false })

db.soap_request_mapping.insert({ "_id" : NumberLong(1029), "end_point_url" : "http://testmsente.utl.co.ug:9081/MSENTEwebService/MsenteTransactionEndpoint?wsdl", "interface_code" : "INTSP0035", "interface_id" : NumberLong(1029), "interface_name" : "MSENTE_DO_BALANCE_INQ", "interface_description" : "MSENTE do balance inquire Response", "interface_type" : "HTTP SOAP", "operation" : "query", "req_attributes" : [ "Token" ], "request" : "<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:int=\"http://interfac.msente.tlc.ph.com/\"><soapenv:Header/><soapenv:Body><int:doBalInq><token>${Token}</token></int:doBalInq></soapenv:Body></soapenv:Envelope>", "system_name" : "MSENTE GATEWAY", "res_attributes" : { "message" : "soapenv:Envelope/soapenv:Body/ns2:doBalInqResponse/return/message", "result" : "soapenv:Envelope/soapenv:Body/ns2:doBalInqResponse/return/result" }, "res_namespace_config" : { "soapenv" : "http://schemas.xmlsoap.org/soap/envelope/", "ns2" : "http://interfac.msente.tlc.ph.com/" }, "tracking_required" : false })
db.soap_request_mapping.insert({ "_id" : NumberLong(1027), "end_point_url" : "http://testmsente.utl.co.ug:9081/MSENTEwebService/MsenteTransactionEndpoint?wsdl", "interface_code" : "INTSP0037", "interface_id" : NumberLong(1027), "interface_name" : "MSENTE_DO_MERCHANT_PAYMENT", "interface_description": "MSENTE do merchant payment Response", "interface_type": "HTTP SOAP", "operation": "query", "req_attributes": ["Token", "toAc", "amount", "sourceRefId", "description"], "request": "<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:int=\"http://interfac.msente.tlc.ph.com/\"><soapenv:Header/><soapenv:Body><int:doMerchantPayment><MsenteTransaction><token>${Token}</token><customerData>${toAc}</customerData><amount>${amount}</amount><operationId>${sourceRefId}</operationId><operationDesc>${description}</operationDesc></MsenteTransaction></int:doMerchantPayment></soapenv:Body></soapenv:Envelope>", "system_name": "MSENTE GATEWAY", 	"res_attributes": { "counter": "soapenv:Envelope/soapenv:Body/ns2:doMerchantPaymentResponse/return/MsenteResponse/counter", "message": "soapenv:Envelope/soapenv:Body/ns2:doMerchantPaymentResponse/return/MsenteResponse/message", "result": "soapenv:Envelope/soapenv:Body/ns2:doMerchantPaymentResponse/return/MsenteResponse/result" }, "res_namespace_config": { "soapenv": "http://schemas.xmlsoap.org/soap/envelope/", "ns2": "http://interfac.msente.tlc.ph.com/" }, "notification" : [{"publish" : true,"subject" : "","media" : "email","language" : "en","template" : "payment_failure"}],"tracking_required": false } )
db.soap_request_mapping.insert({ "_id" : NumberLong(1037), "end_point_url" : "http://testmsente.utl.co.ug:9081/MSENTEwebService/MsenteTransactionEndpoint?wsdl", "interface_code" : "INTSP0047", "interface_id" : NumberLong(1037), "interface_name" : "MSENTE_DO_BILL_PAYMENT", "interface_description": "MSENTE do Bill Payment Response", "interface_type": "HTTP SOAP", "operation": "query", "req_attributes": ["Token", "toAc", "amount", "sourceRefId", "description", "billProvider", "accountNumber", "data1", "data2"], "request": "<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:int=\"http://interfac.msente.tlc.ph.com/\"><soapenv:Header/><soapenv:Body><int:doBillPayment><MsenteTransaction><token>${Token}</token><amount>${amount}</amount><customerData>${toAc}</customerData><operationId>${sourceRefId}</operationId><operationDesc>${description}</operationDesc><billDetails><billProvider>${billProvider}</billProvider><acctNumber>${accountNumber}</acctNumber><data1>${data1}</data1><data2>${data2}</data2></billDetails></MsenteTransaction></int:doBillPayment></soapenv:Body></soapenv:Envelope>", "system_name": "MSENTE GATEWAY", "res_attributes": { "counter": "soap:Envelope/soap:Body/ns2:doBillPaymentResponse/return/MsenteResponse/counter", "message": "soap:Envelope/soap:Body/ns2:doBillPaymentResponse/return/MsenteResponse/message", "result": "soap:Envelope/soap:Body/ns2:doBillPaymentResponse/return/MsenteResponse/result" }, "res_namespace_config": { "soap": "http://schemas.xmlsoap.org/soap/envelope/", "ns2": "http://interfac.msente.tlc.ph.com/" }, "notification" : [{ "publish" : true, "subject" : "", "media" : "email","language" : "en", "template" : "payment_failure"}], "tracking_required": false })
